name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main              # Trigger action on push to main
    paths:
      - 'index.html'      # Only trigger if index.html changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy to GitHub Pages using peaceiris action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploy from the root folder (where index.html is)
