name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger action on push to main
    paths:
      - 'index.html'  # Only trigger if index.html changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Pages deploy action
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token is provided
          publish_dir: ./  # Path to your directory with index.html
